[package]
name = "sniper"
version = "0.1.0"
authors = ["Alexander Fedosov <alexander.a.fedosov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"